export const MSG_CONST = {
  DELETED_TASK_ERROR: 'Erro ao excluir a tarefa.',
  DELETED_TASK_OK: 'Tarefa excluída com sucesso!',
  DELETED_USER_ERROR: 'Erro ao excluir o usuário.',
  DELETED_USER_OK: 'Usuário excluído com sucesso!',
  INVALID_CREDENTIALS: 'E-mail ou senha inválidos.',
  LOGIN_OK: 'Login realizado com sucesso!',
  LOGOUT_OK: 'Você saiu da conta.',
  NOT_AVAILABLE: 'Função indisponível nessa versão.',
  SAVE_DATA_ERROR: 'Erro ao salvar os dados.',
  SAVE_DATA_OK: 'Dados salvos!',
  PROFILE_OK: 'Perfil atualizado!',
  THEME_LIGHT: 'Tema claro ativado.',
  THEME_DARK: 'Tema escuro ativado.',
};
