import { TaskModel } from '../models/task-model';
import { UserModel } from '../models/user-model';
import { TASK_STATUS } from './task-status';

function localDate(year: number, month: number, day: number): Date {
  return new Date(year, month - 1, day);
}

export const MOCK_USERS: UserModel[] = [
  {
    id: '100',
    name: 'Ramon Oliveira',
    email: 'admin@tasktrack.com',
    password: 'admin123',
    role: 'admin',
    gender: 'male',
    registerDate: localDate(2026, 1, 10),
  },
  {
    id: '101',
    name: 'Alice Johnson',
    email: 'alice@gmail.com',
    password: 'user123',
    role: 'user',
    gender: 'female',
    registerDate: localDate(2026, 3, 1),
  },
  {
    id: '102',
    name: 'Bob Smith',
    email: 'bob.smith@example.com',
    password: 'admin123',
    role: 'admin',
    gender: 'male',
    registerDate: localDate(2026, 3, 2),
  },
  {
    id: '103',
    name: 'Carol White',
    email: 'carol.white@example.com',
    password: 'user123',
    role: 'admin',
    gender: 'female',
    registerDate: localDate(2026, 2, 12),
  },
  {
    id: '104',
    name: 'Emma Davis',
    email: 'emma.davis@example.com',
    password: 'user123',
    role: 'user',
    gender: 'female',
    registerDate: localDate(2026, 4, 3),
  },
  {
    id: '105',
    name: 'Grace Wilson',
    email: 'grace.wilson@gmail.com',
    password: 'user123',
    role: 'user',
    gender: 'female',
    registerDate: localDate(2026, 4, 1),
  },
  {
    id: '106',
    name: 'Henry Clark',
    email: 'henry.clark@example.com',
    password: 'user123',
    role: 'user',
    gender: 'male',
    registerDate: localDate(2026, 3, 23),
  },
];

export const MOCK_TASKS: TaskModel[] = [
  {
    id: '1',
    title: 'Criar landing page',
    description: 'Design and implement the new product landing page.',
    expirationDate: localDate(2026, 9, 18),
    registerDate: localDate(2026, 8, 20),
    progress: 50,
    status: TASK_STATUS.IN_PROGRESS,
    responsibleId: '101',
    responsible: MOCK_USERS[1],
  },
  {
    id: '2',
    title: 'Backup do banco de dados',
    description: 'Run a full backup of the production database.',
    expirationDate: localDate(2026, 9, 5),
    registerDate: localDate(2026, 8, 28),
    progress: 100,
    status: TASK_STATUS.DONE,
    responsibleId: '102',
    responsible: MOCK_USERS[2],
  },
  {
    id: '3',
    title: 'Atualizar documentação da API',
    description: 'Update the API documentation with the latest endpoints.',
    expirationDate: localDate(2026, 9, 22),
    registerDate: localDate(2026, 9, 1),
    progress: 25,
    status: TASK_STATUS.PENDING,
    responsibleId: '103',
    responsible: MOCK_USERS[3],
  },
  {
    id: '4',
    title: 'Testes de performance',
    description: 'Run performance tests on the new application release.',
    expirationDate: localDate(2026, 9, 16),
    registerDate: localDate(2026, 9, 2),
    progress: 75,
    status: TASK_STATUS.IN_PROGRESS,
    responsibleId: '104',
    responsible: MOCK_USERS[4],
  },
  {
    id: '5',
    title: 'Revisão de código',
    description: 'Review pull requests submitted by the development team.',
    expirationDate: localDate(2026, 9, 8),
    registerDate: localDate(2026, 9, 3),
    progress: 100,
    status: TASK_STATUS.DONE,
    responsibleId: '101',
    responsible: MOCK_USERS[1],
  },
  {
    id: '6',
    title: 'Auditoria de segurança',
    description: 'Conduct a security audit of the web application.',
    expirationDate: localDate(2026, 9, 8),
    registerDate: localDate(2026, 9, 4),
    progress: 10,
    status: TASK_STATUS.PENDING,
    responsibleId: '106',
    responsible: MOCK_USERS[6],
  },
  {
    id: '7',
    title: 'Análise de feedback',
    description: 'Analyze user feedback from the latest survey.',
    expirationDate: localDate(2026, 9, 24),
    registerDate: localDate(2026, 9, 5),
    progress: 60,
    status: TASK_STATUS.IN_PROGRESS,
    responsibleId: '104',
    responsible: MOCK_USERS[4],
  },
  {
    id: '8',
    title: 'Revisão de UI/UX',
    description: 'Review and refine the mobile app UI/UX design.',
    expirationDate: localDate(2026, 9, 30),
    registerDate: localDate(2026, 9, 6),
    progress: 20,
    status: TASK_STATUS.PENDING,
    responsibleId: '106',
    responsible: MOCK_USERS[6],
  },
  {
    id: '9',
    title: 'Manutenção dos servidores',
    description: 'Perform routine maintenance on the application servers.',
    expirationDate: localDate(2026, 9, 14),
    registerDate: localDate(2026, 9, 7),
    progress: 35,
    status: TASK_STATUS.IN_PROGRESS,
    responsibleId: '102',
    responsible: MOCK_USERS[2],
  },
  {
    id: '10',
    title: 'Lançar campanha de marketing',
    description: 'Launch the new marketing campaign for the upcoming product.',
    expirationDate: localDate(2026, 10, 1),
    registerDate: localDate(2026, 9, 8),
    progress: 40,
    status: TASK_STATUS.PENDING,
    responsibleId: '105',
    responsible: MOCK_USERS[5],
  },
];
